### PR TITLE
(feat) rely on buffer package to polyfill buffer on browsers

### PR DESCRIPTION
**Pull request by oshaikh13**
Not sure if you want this, given that your package was written explicitly for Node.js. This adds a polyfill to fix the missing Buffer class on browsers

### CODE REVIEW

**Comment by danielgindi** [comment]
That would be nice for users like you who need this for the browser!
Could you make that an optional dependency? (optionalDependencies, try-catch require)

**Comment by oshaikh13** [comment]
I don't think optionalDependencies is necessary, because the buffer package won't fail to install or not exist in npm/yarn. I already have a check in there -- if Buffer doesn't exist (on the browser or some old version of node), then we just import the buffer replacement with require. 

https://docs.npmjs.com/files/package.json#optionaldependencies

My understanding is that the "try-catch" is useful only if our buffer replacement doesn't exist (which it does). If I'm understanding this wrong, lemme know! Again, thanks a ton for this library!

**Comment by danielgindi** [comment]
The point is that most users will not want to add another dependency to their project.
Think about people that also do a `rollup`/`pkg`/other_packaging_system. Why add the overhead?
Polyfills should always be optional :-)

**Comment by oshaikh13** [comment]
Yea, I see. The problem is that, regardless of being on the browser or on node, the buffer polyfill installs successfully -- so optionalDependencies really doesn't do anything.

I don't think there's a smarter "conditional dependencies" thing we could use.

**Comment by danielgindi** [comment]
There is `peerDependencies`, which do not get installed automatically, but gets kind of a warning in the console while installing, notifying the user that a peer dependency is missing.

Actually it does not need to really be any kind of dependency, as a user working with buffers in the browser will already have that module. All you need is a try-catch.
Maybe first check if Buffer is available in the global scope, and then try to `require`.

**Comment by oshaikh13** [comment]
That makes sense! Just committed, let me know what you think!

**Comment by oshaikh13** [comment]
Actually, there's still more polyfill we need. Checking endianness and arch need some extra code too. Let me know if you think it's worth making these changes to your repo (I have them on my fork, but I think you're correctly wary that we shouldn't pollute this with warnings for extra random dependencies)

**Comment by danielgindi** [comment]
Yes of course if you've already done this it would be great. Just make it conditional (If process is available...)

**Comment by danielgindi** [comment]
Implemented in 1.1.0

**Pull request closed without merging**
